# Generated by Django 4.0.5 on 2022-09-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_alter_order_num_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_place',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.order'),
        ),
    ]
